// Build script — generates config.js from env vars (Vercel) or .env (local).
// Runs during Vercel build, and locally via `node build.js`.

const fs = require('fs');
const path = require('path');

// Load .env locally (Vercel injects env vars natively, no .env needed)
const envPath = path.join(__dirname, '.env');
if (fs.existsSync(envPath)) {
    fs.readFileSync(envPath, 'utf8').split('\n').forEach(line => {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) return;
        const eq = trimmed.indexOf('=');
        if (eq === -1) return;
        const key = trimmed.slice(0, eq).trim();
        const value = trimmed.slice(eq + 1).trim().replace(/^["']|["']$/g, '');
        if (!process.env[key]) process.env[key] = value;
    });
}

const config = {
    publicKey: process.env.EMAILJS_PUBLIC_KEY || '',
    serviceId: process.env.EMAILJS_SERVICE_ID || '',
    trainerTemplateId: process.env.EMAILJS_TRAINER_TEMPLATE_ID || '',
    clientTemplateId: process.env.EMAILJS_CLIENT_TEMPLATE_ID || '',
    trainerEmail: process.env.TRAINER_EMAIL || 'coach@getontrack.com'
};

const output = `// Auto-generated by build.js — do not edit manually.\nwindow.EMAILJS_CONFIG = ${JSON.stringify(config, null, 2)};\n`;

fs.writeFileSync(path.join(__dirname, 'config.js'), output);
console.log('config.js generated successfully.');
console.log('Public key configured:', config.publicKey ? 'yes' : 'no (booking will skip email)');
